package controllers

import play.api.db.Database
import play.api.i18n.MessagesApi
import play.api.mvc._

class Application(val db: Database, val messagesApi: MessagesApi) extends Controller with LegacyI18nSupport {

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }

  def login = Action { request =>
    // Initializes a database connection using Play's built-in Database API
    db.withConnection { connection =>
      val sql: DSLContext =
        // Creates a jOOQ DSLContext using the transaction
        DSL.using(connection, SQLDialect.POSTGRES_9_4)
      // Fetches all users into classes of the type UserRecord, generated by jOOQ
      val users = context.selectFrom[UserRecord](USER).fetch()
      // Displays the result as a response
      Ok(users.toString)
    }
  }

}
